class_name PlayerStats
extends Object

enum {
	HEALTH,
	DASH_COOLDOWN,
	SPELL_SLOTS,
	SPELL_COOLDOWN,
	SPELL_SIZE,
	SPELL_SPEED,
	SPELL_DAMAGE,
	SPELL_HOMING,
	DODGE_CHANCE,
	DAMAGE_TAKEN,
	IFRAME_DURATION,
	MOVE_SPEED,
}

static var base = {
	HEALTH: 4,
	DASH_COOLDOWN: 1.0,
	SPELL_SLOTS: 4,
	SPELL_COOLDOWN: 1.0,
	SPELL_SIZE: 0,
	SPELL_SPEED: 1.0,
	SPELL_DAMAGE: 1.0,
	SPELL_HOMING: 0.0,
	DODGE_CHANCE: 0.0,
	DAMAGE_TAKEN: 1.0,
	IFRAME_DURATION: 1.0,
	MOVE_SPEED: 1.0,
}
